# Generated by Django 5.1.5 on 2025-01-22 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('app_label', models.CharField(max_length=100)),
                ('is_full_app', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='search_history',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_unique_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='can_manage_roles',
            field=models.BooleanField(default=False, help_text='Can manage roles for this vendor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.currency'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_vendor_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AppModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.appmodule')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='HousingChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='housing_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.housingchoice'),
        ),
        migrations.CreateModel(
            name='HousingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.currency')),
                ('housing_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.housingchoice')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.currency')),
            ],
            options={
                'unique_together': {('country', 'currency', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='income_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.incomechoice'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.vendor')),
            ],
            options={
                'unique_together': {('user', 'role', 'vendor')},
            },
        ),
        migrations.DeleteModel(
            name='RoleManager',
        ),
    ]
